server:
  port: 8088

spring:
  application:
    name: springcloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lv494966388/springcloud-test-config.git
          search-paths: /
      label: master

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
